### ISSUE TITLE
Support ZIMPL files

### ISSUE THREAD

**Issue by zeljkoavramovic** [avk959/LazLpSolveIDE#2]
What would need to be done to extend support to XLI XIMPL *.zpl files, which C++ lpsolve IDE already supports?

**Comment by avk959** [comment]
AFAIK, if you mean the Zimpl language, you need the appropriate xli_Zimpl driver and make sure that the LpSolveIDE.ini file contains a description of this xli.

**Comment by zeljkoavramovic** [comment]
After unpacking "lp_solve_5.5.2.5_exe_win32.zip" (command line version with needed DLL plugins) to LazLpSolve executable directory and copying "LpSolveIDE.ini" from C++ IDE version, loading of XLI ZIMPL (*.zpl) language file works.

Here is Chatal's diet example converted by me from ZPL to LP format:

```
// Minimize cost:
min: 3 Oatmeal + 24 Chicken + 13 Eggs + 9 Milk + 20 Pie + 19 Pork;

// Nutritients:
Energy:    110 Oatmeal + 205 Chicken + 160 Eggs + 160 Milk + 420 Pie + 260 Pork > 2000;
Protein:     4 Oatmeal +  32 Chicken +  13 Eggs +   8 Milk +   4 Pie +  14 Pork >   55;
Calcium:     2 Oatmeal +  12 Chicken +  54 Eggs + 284 Milk +  22 Pie +  80 Pork >  800;

// Servings:
0 <= Oatmeal <= 4;
0 <= Chicken <= 3;
0 <= Eggs    <= 2;
0 <= Milk    <= 8;
0 <= Pie     <= 2;
0 <= Pork    <= 2;

// Variable types:
int Oatmeal, Chicken, Eggs, Milk, Pie, Pork; 
```
That example is very nice since it can be used as a base for something like cost optimization of any industrial production recipe.

Thank you very much!

[INI file to enable other file types with DLL plugins.zip](https://github.com/avk959/LazLpSolveIDE/files/4605468/INI.file.to.enable.other.file.types.with.DLL.plugins.zip)
